version: '3'

services:
  amsterdam:
    build: 
      context: .
      dockerfile: Dockerfile.dev

    volumes:
      - ./src/configs/amsterdam.sqlite:/usr/src/data/amsterdam.sqlite
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies

    ports:
      - "3000:3000"