version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5433:5432"  # Porta da App/ Porta do Host
    env_file:
      - .env
    volumes:
      - ./src/configs/init.sql:/docker-entrypoint-initdb.d/init.sql
